// flow-typed signature: 7b44a396e60f16f831749e50e3e7f3ff
// flow-typed version: <<STUB>>/serve_v^10.1.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serve/bin/serve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serve/bin/serve.js' {
  declare module.exports: $Exports<'serve/bin/serve'>;
}
